### ISSUE TITLE
TF with python3

### ISSUE THREAD

**Issue by IoannisDadiotis** [ADVRHumanoids/casannis_walking#6]
Hi @alaurenzi ,
I want your suggestion with this. I am trying to interface a [tf listener](https://github.com/ADVRHumanoids/casannis-walking/blob/master/src/tf_listener.py) with [my demo script](https://github.com/ADVRHumanoids/casannis-walking/blob/master/src/demo_action_server.py) but when I run the latter I get the following error:
```
Traceback (most recent call last):
  File "/home/ioannis/centauro_ws/src/casannis_walking/src/demo_action_server.py", line 9, in <module>
    from tf_listener import get_transform
  File "/home/ioannis/centauro_ws/src/casannis_walking/src/tf_listener.py", line 4, in <module>
    import tf
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/home/ioannis/centauro_ws/devel/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
  File "/home/ioannis/centauro_ws/devel/lib/python2.7/dist-packages/tf2_py/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
ImportError: dynamic module does not define module export function (PyInit__tf2)
```
I think tf (and tf2) have as a default interpreter python2 and this causes the problem as my code in the current package is interpreted with python3. Now, this seems a known issue (e.g. [here](https://github.com/ros/geometry2/issues/293) and [here](https://github.com/ros/geometry2/issues/259)). 

I tried to follow the answer of [this](https://answers.ros.org/question/326226/importerror-dynamic-module-does-not-define-module-export-function-pyinit__tf2/), compiling my whole workspace with python3 (which is not the default with the ros version I am using), but, then, I got another issue: I could not run the `urdf_spawner`. After this, I quitted this effort, as I suppose this may rise many problems in my workspace (with python2-based scripts), and recompiled my workspace with the default python interpreter. What do you suggest ?

**Comment by alaurenzi** [comment]
Unfortunately, full support for ROS + Python3 needs Ubuntu 20.04

**Comment by IoannisDadiotis** [comment]
Do you suggest to switch the code to python 2?
